### ISSUE TITLE
UnboundLocalError for 'pairs' - pcap_utils.py

### ISSUE THREAD

**Issue by jaiken06** [CyberReboot/PoseidonML#91]
Whilst trying to train a model I encountered the following error:

```
root@d3499990ed37:/app/NodeClassifier# python train_OneLayer.py ./Training firsttest.pickle
Reading data
Reading ./Training/WebTraffic-test.pcap as WebTraffic
Traceback (most recent call last):
  File "train_OneLayer.py", line 31, in <module>
    model.train(data_dir)
  File "/app/NodeClassifier/utils/OneLayer.py", line 133, in train
    labels=self.labels
  File "/app/NodeClassifier/utils/training_utils.py", line 67, in read_data
    capture_source = get_source(binned_sessions)
  File "/app/NodeClassifier/utils/pcap_utils.py", line 140, in get_source
    _, ip_mac_pairs = get_indiv_source(session_dict)
  File "/app/NodeClassifier/utils/pcap_utils.py", line 88, in get_indiv_source
    if is_private(source_address) or is_private(destination_address):
  File "/app/NodeClassifier/utils/pcap_utils.py", line 24, in is_private
    if pairs[0] == '10': private = True
UnboundLocalError: local variable 'pairs' referenced before assignment
```

Why would the pairs variable not be assigned?  From what I gathered reading pcap_utils, the address needs to be equal to or greater than 4 for 'pairs' to get set, would would cause the address argument to be less than that?

**Comment by cglewis** [comment]
@jaiken06 this has been fixed in the `overhaul` branch, which isn't quite ready for merging into master yet as it's a big structural change.  let me push that fix into master in the meantime.
